- name: oVirt infra
  hosts: all
  gather_facts: false

  vars:
    engine_url: https://rhvm.epc.ext.hpe.com/ovirt-engine/api
    engine_user: admin@internal
    engine_password: 123456
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    hana_vm:
      cluster: production
      root_password: 123456
      domain: example.com
      template: rhel7
      memory: 4GiB
      cores: 2
      state: running

   affinity_groups:
      - name: db-ag
        cluster: production 
        vm_enforcing: true
        vm_rule: negative
        vms:
          - postgresql-vm-0
          - postgresql-vm-1

    vms:
      - name: apache-vm-1
        tag: httpd
        profile: "{{ hana_vm }}"

  roles:
          - {{ role: oVirt.vm-infra }}
          - rhv-create-hana-env
